# Generated by Django 3.1 on 2024-11-25 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.TextField(verbose_name='Set #')),
                ('reps', models.IntegerField(verbose_name='Reps')),
                ('min_in_w_o', models.IntegerField(verbose_name='Min in W/O')),
            ],
        ),
    ]
