# Generated by Django 3.1 on 2024-11-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model1',
            name='set_number',
            field=models.CharField(max_length=100, verbose_name='Set #'),
        ),
    ]
